/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as QuantumPrimerRouteImport } from './routes/quantum-primer'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as DeckIndexRouteImport } from './routes/deck.index'
import { Route as DeckSlideRouteImport } from './routes/deck.$slide'
import { Route as DeckPrintRouteImport } from './routes/deck.print'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase.index'
import { Route as ThemesIndexRouteImport } from './routes/themes.index'
import { Route as ThemesThemeRouteImport } from './routes/themes.$theme'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumPrimerRoute = QuantumPrimerRouteImport.update({
  id: '/quantum-primer',
  path: '/quantum-primer',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIndexRoute = DeckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeckRoute,
} as any)
const DeckSlideRoute = DeckSlideRouteImport.update({
  id: '/$slide',
  path: '/$slide',
  getParentRoute: () => DeckRoute,
} as any)
const DeckPrintRoute = DeckPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => DeckRoute,
} as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThemesRoute,
} as any)
const ThemesThemeRoute = ThemesThemeRouteImport.update({
  id: '/$theme',
  path: '/$theme',
  getParentRoute: () => ThemesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deck': typeof DeckRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/deck/$slide': typeof DeckSlideRoute
  '/deck/print': typeof DeckPrintRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/deck/': typeof DeckIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/strategy': typeof StrategyRoute
  '/deck/$slide': typeof DeckSlideRoute
  '/deck/print': typeof DeckPrintRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/deck': typeof DeckIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/themes': typeof ThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deck': typeof DeckRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/quantum-primer': typeof QuantumPrimerRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/strategy': typeof StrategyRoute
  '/themes': typeof ThemesRouteWithChildren
  '/deck/$slide': typeof DeckSlideRoute
  '/deck/print': typeof DeckPrintRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/themes/$theme': typeof ThemesThemeRoute
  '/deck/': typeof DeckIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/themes/': typeof ThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/deck'
    | '/llms-full.txt'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/deck/$slide'
    | '/deck/print'
    | '/ideas/$id'
    | '/themes/$theme'
    | '/deck/'
    | '/showcase/'
    | '/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/llms-full.txt'
    | '/quantum-primer'
    | '/strategy'
    | '/deck/$slide'
    | '/deck/print'
    | '/ideas/$id'
    | '/themes/$theme'
    | '/deck'
    | '/showcase'
    | '/themes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/deck'
    | '/llms-full.txt'
    | '/quantum-primer'
    | '/showcase'
    | '/strategy'
    | '/themes'
    | '/deck/$slide'
    | '/deck/print'
    | '/ideas/$id'
    | '/themes/$theme'
    | '/deck/'
    | '/showcase/'
    | '/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeckRoute: typeof DeckRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  QuantumPrimerRoute: typeof QuantumPrimerRoute
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  StrategyRoute: typeof StrategyRoute
  ThemesRoute: typeof ThemesRouteWithChildren
  IdeasIdRoute: typeof IdeasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-primer': {
      id: '/quantum-primer'
      path: '/quantum-primer'
      fullPath: '/quantum-primer'
      preLoaderRoute: typeof QuantumPrimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/': {
      id: '/deck/'
      path: '/'
      fullPath: '/deck/'
      preLoaderRoute: typeof DeckIndexRouteImport
      parentRoute: typeof DeckRoute
    }
    '/deck/$slide': {
      id: '/deck/$slide'
      path: '/$slide'
      fullPath: '/deck/$slide'
      preLoaderRoute: typeof DeckSlideRouteImport
      parentRoute: typeof DeckRoute
    }
    '/deck/print': {
      id: '/deck/print'
      path: '/print'
      fullPath: '/deck/print'
      preLoaderRoute: typeof DeckPrintRouteImport
      parentRoute: typeof DeckRoute
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/themes/': {
      id: '/themes/'
      path: '/'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof ThemesRoute
    }
    '/themes/$theme': {
      id: '/themes/$theme'
      path: '/$theme'
      fullPath: '/themes/$theme'
      preLoaderRoute: typeof ThemesThemeRouteImport
      parentRoute: typeof ThemesRoute
    }
  }
}

interface DeckRouteChildren {
  DeckSlideRoute: typeof DeckSlideRoute
  DeckPrintRoute: typeof DeckPrintRoute
  DeckIndexRoute: typeof DeckIndexRoute
}

const DeckRouteChildren: DeckRouteChildren = {
  DeckSlideRoute: DeckSlideRoute,
  DeckPrintRoute: DeckPrintRoute,
  DeckIndexRoute: DeckIndexRoute,
}

const DeckRouteWithChildren = DeckRoute._addFileChildren(DeckRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseIndexRoute: ShowcaseIndexRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface ThemesRouteChildren {
  ThemesThemeRoute: typeof ThemesThemeRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesThemeRoute: ThemesThemeRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeckRoute: DeckRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  QuantumPrimerRoute: QuantumPrimerRoute,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  StrategyRoute: StrategyRoute,
  ThemesRoute: ThemesRouteWithChildren,
  IdeasIdRoute: IdeasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
